config/routes.rb
Codefest::Application.routes.draw do

  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :welcome
  resources :activity_exercise
  get "sessions/create"
  get "sessions/destroy"
  get "nutrition/calorie_counter"
  get "nutrition/weight"
  get "wellness/sleep"
  get "wellness/allergies"
  get "wellness/diabetes"
  get "activity/tv_computer"
  get "activity/exercise_level"
  get "welcome/index"
  get "welcome/show"
  post "welcome/create"

  root to: 'welcome#index'

end

app/models/leisure.rb
class Leisure < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  layout "main"
  def tv_computer
  end

  def exercise_level
    @sports = Sport.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :nav

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def nav
    @activity = 'Activity'
    @activity_sub = ['TV & Computer','Exercise Level']
    @activity_urls = [activity_tv_computer_path, activity_exercise_level_path ]
    @wellness = 'Wellness'
    @wellness_sub = ['Sleep', 'Allergies', 'Diabetes']
    @wellness_urls = [wellness_sleep_path, wellness_allergies_path, wellness_diabetes_path]
    @nutrition = 'Nutrition'
    @nutrition_sub = ['Calorie Counter', 'Weight']
    @nutrition_urls = [nutrition_calorie_counter_path, nutrition_weight_path]
  end


end

app/controllers/nutrition_controller.rb
class NutritionController < ApplicationController
  layout "main"
  def calorie_counter
  end

  def weight
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def create
    @@par = params
    if params[:leisure]
      @leisure = Leisure.new(collection_params)

      @leisure.save
      redirect_to welcome_path(@leisure.id)
    elsif params[:sport]
      @sport = Sport.new(collection_params)

      @sport.save
      redirect_to activity_exercise_level_path
    end
  end

  def show
    if @@par[:leisure]
      @leisure = Leisure.find(params[:id])
    end
  end

  private

  def collection_params

    if params[:leisure]
      params.require(:leisure).permit(:tv_time, :pc_time)
    elsif params[:sport]
      params.require(:sport).permit(:sport_name, :time)
    end
  end

end

app/controllers/wellness_controller.rb
class WellnessController < ApplicationController
  layout "main"
  def sleep
  end

  def allergies
  end

  def diabetes
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nutrition_helper.rb
module NutritionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wellness_helper.rb
module WellnessHelper
end

app/views/activity/exercise_level.html.erb
<h1>Activity#exercise_level</h1>
<p>
  Find me in app/views/activity/exercise_level.html.erb
</p>
<body style="background-color:#DAA520;">
  <h2 style="text-align:center;">Exercise and Fitness</h2>
  <p style="test-align:left;">
    This graph shows your exercise progress through out the week. Stay Healthy!
  </p>
  <div style="font-family:Arial, Helvetica, sans-serif;
  padding:300px;border-radius:20px;border:15px solid #1E90FF;">
    <p>
<% @sports.each do |sport| %>
      <strong>Sport name:</strong>
      <%= sport.sport_name %>
      <%= sport.time %>
    </p>
    <%end%>
</body>

app/views/activity/tv_computer.html.erb
<head>
<style>
h2{text-align:center;}

</style>
</head>
<h1>Activity#tv_computer</h1>


<p>Find me in app/views/activity/tv_computer.html.erb</p>

<body style="background-color:#6633FF;"> 
	<p>Welcome User. Below you will see the graph of how many hours you have spent in front of a T.V. or Computer Screen.</p>
	
</body>

<h2  >Graph of your recent activity</h2>

<div style="font-family:verdana;padding:300px;border-radius:1px;border:10px solid #EE872A;">
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fixed Top Navbar Example for Bootstrap</title>

    <%= stylesheet_link_tag  'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Codefest Webapp</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Home", welcome_index_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @activity%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @activity_sub.each_index do |i| %>
                <li>
                  <%= link_to @activity_sub[i], @activity_urls[i] %>
                </li>
                <% end %> <!-- loop end -->
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @wellness%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @wellness_sub.each_index do |i| %>
                <li>
                  <%= link_to @wellness_sub[i], @wellness_urls[i] %>
                </li>
                <% end %> <!-- loop end -->
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @nutrition%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @nutrition_sub.each_index do |i| %>
                <li>
                  <%= link_to @nutrition_sub[i], @nutrition_urls[i] %>
                </li>
                <% end %> <!-- loop end -->
              </ul>
            </li>
            <li>
              <a href="#about">About</a>
            </li>
            <li>
              <a href="#contact">Contact</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
              <a href="../navbar/"><%= current_user.name %>'s Profile</a>
              <% else %>
              <%end%>
            </li>

            <li>
              <% if current_user %>
              <%= link_to "Sign out", signout_path, id: "sign_out" %>
              <% else %>
              <%= link_to image_tag("Google_login/Red-signin_Long_base_20dp.png", :size => "183x37"), "/auth/google_oauth2", id: "sign_in", style:"padding-bottom:0; padding-top:5px;" %>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <!-- /container -->
      <div class="wrap">
        <%= yield %>
      </div>
      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fixed Top Navbar Example for Bootstrap</title>

    <%= stylesheet_link_tag  'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Codefest Webapp</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Home", welcome_index_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @activity%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @activity_sub.each_index do |i| %>
                <li>
                  <%= link_to @activity_sub[i], @activity_urls[i] %>
                </li>
                <% end %> <!-- loop end -->
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @wellness%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @wellness_sub.each_index do |i| %>
                <li>
                  <%= link_to @wellness_sub[i], @wellness_urls[i] %>
                </li>
                <% end %> <!-- loop end -->
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @nutrition%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @nutrition_sub.each_index do |i| %>
                <li>
                  <%= link_to @nutrition_sub[i], @nutrition_urls[i] %>
                </li>
                <% end %> <!-- loop end -->
              </ul>
            </li>
            <li>
              <a href="#about">About</a>
            </li>
            <li>
              <a href="#contact">Contact</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
              <a href="../navbar/"><%= current_user.name %>'s Profile</a>
              <% else %>
              <%end%>
            </li>

            <li>
              <% if current_user %>
              <%= link_to "Sign out", signout_path, id: "sign_out" %>
              <% else %>
              <%= link_to image_tag("Google_login/Red-signin_Long_base_20dp.png", :size => "183x37"), "/auth/google_oauth2", id: "sign_in", style:"padding-bottom:0; padding-top:5px;" %>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <!-- /container -->
      <div class="wrap">
        <%= yield %>
      </div>
      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/nutrition/calorie_counter.html.erb
<h1>Nutrition#calorie_counter</h1>
<p>Find me in app/views/nutrition/calorie_counter.html.erb</p>
<body style="background-color:#6633FF;"> 
<h2> The graph below will show you how many calories you have consumed over the past week.</h2>

<div style="font-family:verdana;padding:300px;border-radius:1px;border:10px solid pink;">
	
</div>
</body>

app/views/nutrition/weight.html.erb
<h1>Nutrition#weight</h1>
<p>Find me in app/views/nutrition/weight.html.erb</p>
<body style="background-color:#6633FF;"> 
<h2> The graph below will show you how your wait has changed over the past month.</h2>

<div style="font-family:verdana;padding:300px;border-radius:1px;border:10px solid silver;">
	
</div>
</body>

app/views/welcome/index.html.erb
<br />

<%= form_for :leisure, url: welcome_create_path do |f| %>
<p>
  <%= f.label :tv_time %>
  <br>
  <%= f.number_field :tv_time %>
</p>

<p>
  <%= f.label :pc_time %>
  <br>
  <%= f.number_field :pc_time %>
</p>

<p>
  <input type="submit" />
</p>
<% end %>

<br />

<%= form_for :sport, url: welcome_create_path do |f| %>
<p>
  <%= f.label :sport_name %>
  <br>
  <%= f.text_field :sport_name %>
</p>

<p>
  <%= f.label :time %>
  <br>
  <%= f.number_field :time %>
</p>

<p>
  <input type="submit" />
</p>
<% end %>

app/views/welcome/show.html.erb
<br />
<br />
<br />
<p>

  <%if !@leisure.nil?%>
  <strong>Time spent:</strong>
  <%= @leisure.tv_time.to_f + @leisure.pc_time.to_f %>
  <%end%>
</p>

app/views/wellness/allergies.html.erb
<h1>Wellness#allergies</h1>
<p>Find me in app/views/wellness/allergies.html.erb</p>
<body style="background-color:#6633FF;"> 
<h2> The graph below will show you how much of your allergen is present in the air today.</h2>

<div style="font-family:verdana;padding:300px;border-radius:1px;border:10px solid red;">
	
</div>

</body>

app/views/wellness/diabetes.html.erb
<h1>Wellness#diabetes</h1>
<p>Find me in app/views/wellness/diabetes.html.erb</p>

<body style="background-color:#6633FF;"> 
<h2> The graph below will show you your blood pressure readings from the past month.</h2>

<div style="font-family:verdana;padding:300px;border-radius:1px;border:10px solid gold;">
	
</div>
</body>

app/views/wellness/sleep.html.erb
<h1>Wellness#sleep</h1>
<p>Find me in app/views/wellness/sleep.html.erb</p>

<body style="background-color: 	#AFEEEE;">
	<h2 style="text-align:center;">Sleep</h2>
	<p style="test-align:left;">This graph shows how much sleep on average you get per week. Stay well rested!</p>
	<div style="font-family:Arial, Helvetica, sans-serif; 
	padding:300px;border-radius:20px;border:15px solid #191970;">
	
</body>